Repository CSSSR/csssr.com, pull requests merged in 2020-11, with the labels that each got.

#1694 COM-2616-e2e-Pojects
  e2e-tests/nightwatch/screenshots/base/16_QAcademy/02_Screenshots/QAcademy_1024_EN/chrome-1024x3800.png
  e2e-tests/nightwatch/screenshots/base/16_QAcademy/02_Screenshots/QAcademy_1024_RU/chrome-1024x3800.png
  e2e-tests/nightwatch/screenshots/base/16_QAcademy/02_Screenshots/QAcademy_1280_EN/chrome-1280x5300.png
  e2e-tests/nightwatch/screenshots/base/16_QAcademy/02_Screenshots/QAcademy_1280_RU/chrome-1280x5300.png
  e2e-tests/nightwatch/screenshots/base/16_QAcademy/02_Screenshots/QAcademy_1360_EN/chrome-1360x5300.png
  e2e-tests/nightwatch/screenshots/base/16_QAcademy/02_Screenshots/QAcademy_1360_RU/chrome-1360x5300.png
  e2e-tests/nightwatch/screenshots/base/16_QAcademy/02_Screenshots/QAcademy_1920_EN/chrome-1920x4950.png
  e2e-tests/nightwatch/screenshots/base/16_QAcademy/02_Screenshots/QAcademy_1920_RU/chrome-1920x4950.png
  e2e-tests/nightwatch/screenshots/base/16_QAcademy/02_Screenshots/QAcademy_360_EN/chrome-360x5300.png
  e2e-tests/nightwatch/screenshots/base/16_QAcademy/02_Screenshots/QAcademy_360_RU/chrome-360x5300.png
  e2e-tests/nightwatch/screenshots/base/17_Brusnika/02_Screenshots/Brusnika_1024_EN/chrome-1024x3800.png
  e2e-tests/nightwatch/screenshots/base/17_Brusnika/02_Screenshots/Brusnika_1024_RU/chrome-1024x3800.png
  e2e-tests/nightwatch/screenshots/base/17_Brusnika/02_Screenshots/Brusnika_1280_EN/chrome-1280x5300.png
  e2e-tests/nightwatch/screenshots/base/17_Brusnika/02_Screenshots/Brusnika_1280_RU/chrome-1280x5300.png
  e2e-tests/nightwatch/screenshots/base/17_Brusnika/02_Screenshots/Brusnika_1360_EN/chrome-1360x5300.png
  e2e-tests/nightwatch/screenshots/base/17_Brusnika/02_Screenshots/Brusnika_1360_RU/chrome-1360x5300.png
  e2e-tests/nightwatch/screenshots/base/17_Brusnika/02_Screenshots/Brusnika_1920_EN/chrome-1920x4950.png
  e2e-tests/nightwatch/screenshots/base/17_Brusnika/02_Screenshots/Brusnika_1920_RU/chrome-1920x4950.png
  e2e-tests/nightwatch/screenshots/base/17_Brusnika/02_Screenshots/Brusnika_360_EN/chrome-360x5300.png
  e2e-tests/nightwatch/screenshots/base/17_Brusnika/02_Screenshots/Brusnika_360_RU/chrome-360x5300.png
  e2e-tests/nightwatch/screenshots/base/18_MindBox/02_Screenshots/Mindbox_1024_EN/chrome-1024x3800.png
  e2e-tests/nightwatch/screenshots/base/18_MindBox/02_Screenshots/Mindbox_1024_RU/chrome-1024x3800.png
  e2e-tests/nightwatch/screenshots/base/18_MindBox/02_Screenshots/Mindbox_1280_EN/chrome-1280x5300.png
  e2e-tests/nightwatch/screenshots/base/18_MindBox/02_Screenshots/Mindbox_1280_RU/chrome-1280x5300.png
  e2e-tests/nightwatch/screenshots/base/18_MindBox/02_Screenshots/Mindbox_1360_EN/chrome-1360x5300.png
  e2e-tests/nightwatch/screenshots/base/18_MindBox/02_Screenshots/Mindbox_1360_RU/chrome-1360x5300.png
  e2e-tests/nightwatch/screenshots/base/18_MindBox/02_Screenshots/Mindbox_1920_EN/chrome-1920x4950.png
  e2e-tests/nightwatch/screenshots/base/18_MindBox/02_Screenshots/Mindbox_1920_RU/chrome-1920x4950.png
  e2e-tests/nightwatch/screenshots/base/18_MindBox/02_Screenshots/Mindbox_360_EN/chrome-360x5300.png
  e2e-tests/nightwatch/screenshots/base/18_MindBox/02_Screenshots/Mindbox_360_RU/chrome-360x5300.png
  e2e-tests/nightwatch/screenshots/base/19_MosoblGaz/02_Screenshots/Mosoblgaz_1024_EN/chrome-1024x3800.png
  e2e-tests/nightwatch/screenshots/base/19_MosoblGaz/02_Screenshots/Mosoblgaz_1024_RU/chrome-1024x3800.png
  e2e-tests/nightwatch/screenshots/base/19_MosoblGaz/02_Screenshots/Mosoblgaz_1280_EN/chrome-1280x5300.png
  e2e-tests/nightwatch/screenshots/base/19_MosoblGaz/02_Screenshots/Mosoblgaz_1280_RU/chrome-1280x5300.png
  e2e-tests/nightwatch/screenshots/base/19_MosoblGaz/02_Screenshots/Mosoblgaz_1360_EN/chrome-1360x5300.png
  e2e-tests/nightwatch/screenshots/base/19_MosoblGaz/02_Screenshots/Mosoblgaz_1360_RU/chrome-1360x5300.png
  e2e-tests/nightwatch/screenshots/base/19_MosoblGaz/02_Screenshots/Mosoblgaz_1920_EN/chrome-1920x4950.png
  e2e-tests/nightwatch/screenshots/base/19_MosoblGaz/02_Screenshots/Mosoblgaz_1920_RU/chrome-1920x4950.png
  e2e-tests/nightwatch/screenshots/base/19_MosoblGaz/02_Screenshots/Mosoblgaz_360_EN/chrome-360x5300.png
  e2e-tests/nightwatch/screenshots/base/19_MosoblGaz/02_Screenshots/Mosoblgaz_360_RU/chrome-360x5300.png
  e2e-tests/nightwatch/tests/16 QAcademy/01 Sending request.test.js
  e2e-tests/nightwatch/tests/16 QAcademy/02 Screenshots.test.js
  e2e-tests/nightwatch/tests/16 QAcademy/03 Routs.test.js
  e2e-tests/nightwatch/tests/17 Brusnika/01 Sending request.test.js
  e2e-tests/nightwatch/tests/17 Brusnika/02 Screenshots.test.js
  e2e-tests/nightwatch/tests/17 Brusnika/03 Routs.test.js
  e2e-tests/nightwatch/tests/18 MindBox/01 Sending request.test.js
  e2e-tests/nightwatch/tests/18 MindBox/02 Screenshots.test.js
  e2e-tests/nightwatch/tests/18 MindBox/03 Routs.test.js
  e2e-tests/nightwatch/tests/19 MosoblGaz/01 Sending request.test.js
  e2e-tests/nightwatch/tests/19 MosoblGaz/02 Screenshots.test.js
  e2e-tests/nightwatch/tests/19 MosoblGaz/03 Routs.test.js
  e2e-tests/nightwatch/tests/actions/bubbleContInfo.js
Labels: e2e-tests

#1688 COM-2869-e2e_LAUNCH_URL-update
  e2e-tests/e2e-tools.json
Labels: e2e-tests

#1705 [COM-2122]: Changed adress cursor
  components/Footer/DoubleBottom/Addresses/Addresses.styles.js
Labels: bug

#1706 COM-2895: Fix vacancies data-testid
  components/main/Vacancies/Vacancies.jsx
Labels: e2e

#1708 [COM-2879]: Changed popup close button
  components/contact-us/ContactUs/BookACall/CalendlyBookingButton/CalendlyBookingButton.styles.js
Labels: bug

#1738 [COM-2947]: Change job page font styles
  components/job/CandidateForm/CandidateForm.jsx
  components/job/CandidateForm/CandidateForm.styles.js
  components/job/section-types/TitleAndList/TitleAndList.styles.js
Labels: bug

#1707 [COM-2724]: Changed adress field indents
  components/contact-us/ContactUs/Map/Address/Address.styles.js
  static/locales/ru/contactUs.json
Labels: bug

#1741 [COM-2360]: Add target blank to policy links
  components/Footer/PrivacyAndLanguageLinks/PrivacyAndLanguageLinks.jsx
  components/Footer/PrivacyAndLanguageLinks/PrivacyAndLanguageLinks.styles.js
Labels: bug

#1747 [COM-2898]: Remove pseudo element from external\internal link
  components/projects/Solutions/Solutions.jsx
  components/projects/Solutions/Solutions.styles.js
Labels: bug

#1755 fix(Idea): COM-2939 add will-change
  components/Idea/Idea.styles.js
Labels: wip
